# -*- coding: utf-8 -*-
"""Weather_please_bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q3RhVC94xPOHati8eiUeNzFwIBYJpxxG
"""

# !pip install pyowm
# !pip install pyTelegramBotAPI==3.7.3

from pyowm import OWM
import telebot


owm = OWM()
obs = owm.weather_at_place()
w = obs.get_weather()
w.get_temperature(unit='celsius')

bot = telegram.TeleBot()

@bot.message_handler(commands=['start', 'help'])
def commands(message):
  if message.text == '/start':
	  bot.send_message(message.from_user.id, """Привет! Я могу найти тебе погоду в нужном городе. Условие:
1. Никому не рассказывай о бойцовском клубе 
2. Пиши в подобном формате 'Москва, РФ' или 'Москва'
3. Только на русском языке
У меня есть чувство, что мы с тобой сработаемся.
""")
  elif message.text == '/help':
    bot.send_message(message.from_user.id, """Смотри. Ты поможешь мне, я помогу тебе:
1. Я понимаю только в формате, подобном этому — 'Москва, РФ' или 'Москва'
2. Если я не отвечаю, то здесь две причины: или меня отключили, или ты вводишь город/страну не в том формате. 
Но я тебе пишу, верно? Значит с меня взятки гладки.
""")

@bot.message_handler(content_types=['text'])
def handle_messages(message):
  obs = owm.weather_at_place(message.text)
  w = obs.get_weather()
  now_temp = w.get_temperature(unit='celsius')
  status = w.get_detailed_status()
  bot.send_message(message.from_user.id, f'''Температура в {message.text} следующая:
Минимальная температура: {now_temp.get("temp_min")}С
Средняя температура: {now_temp.get("temp")}С
Максимальная температура: {now_temp.get("temp_max")}C
На небе: {status}
''')

bot.polling()
